deployment:
  tasks:
    - export DEPLOYPATH=/home/chumuvep/public_html/wolf
    - /bin/mkdir -p "$DEPLOYPATH"

    # Clean deploy folder but preserve common host-managed items if present
    - /usr/bin/find "$DEPLOYPATH" -mindepth 1 -maxdepth 1 ! -name '.well-known' ! -name 'cgi-bin' ! -name '.htaccess' -exec /bin/rm -rf {} +

    # IMPORTANT: Checkout the repo HEAD into the deploy path.
    # This works even if cPanel uses a bare repo (where ./ contains objects/refs/HEAD).
    - /usr/bin/git --work-tree="$DEPLOYPATH" checkout -f HEAD

    # Remove anything that should never be web-served (extra safety)
    - /bin/rm -rf \
      "$DEPLOYPATH/.git" \
      "$DEPLOYPATH/.github" \
      "$DEPLOYPATH/.cpanel.yml" \
      "$DEPLOYPATH/.DS_Store" \
      "$DEPLOYPATH/.gitattributes" \
      "$DEPLOYPATH/README.md" \
      "$DEPLOYPATH/LICENSE"
