deployment:
  tasks:
    # Deploy Wolf app to chumworx.com/wolf
    - export DEPLOYPATH=/home/chumuvep/public_html/wolf
    - /bin/mkdir -p "$DEPLOYPATH"

    # Mirror repo -> deploy folder (reliable, no need to maintain a file copy list)
    # Preserves host-managed folders/files if they exist: .well-known, cgi-bin, .htaccess
    - /usr/bin/rsync -a --delete \
        --exclude ".git/" \
        --exclude ".github/" \
        --exclude ".DS_Store" \
        --exclude ".cpanel.yml" \
        --exclude ".well-known/" \
        --exclude "cgi-bin/" \
        --exclude ".htaccess" \
        ./ "$DEPLOYPATH/"
