deployment:
  tasks:

    # ------------------------------------------------------------
    # 1) Define where the live site should be deployed
    #    This is your public web folder for:
    #    https://chumworx.com/wolf/
    # ------------------------------------------------------------
    - export DEPLOYPATH=/home/chumuvep/public_html/wolf

    # Ensure the deploy directory exists
    - /bin/mkdir -p "$DEPLOYPATH"


    # ------------------------------------------------------------
    # 2) Clean the deploy folder before copying new files
    #    - Removes everything inside /wolf
    #    - Preserves host-managed folders if they exist
    #      (.well-known, cgi-bin, .htaccess)
    # ------------------------------------------------------------
    - /usr/bin/find "$DEPLOYPATH" -mindepth 1 -maxdepth 1 \
        ! -name '.well-known' \
        ! -name 'cgi-bin' \
        ! -name '.htaccess' \
        -exec /bin/rm -rf {} +


    # ------------------------------------------------------------
    # 3) Deploy the current Git HEAD to the web folder
    #    This exports only tracked repo files.
    #    Works correctly even if the repo is bare.
    # ------------------------------------------------------------
    - /usr/bin/git --work-tree="$DEPLOYPATH" checkout -f HEAD


    # ------------------------------------------------------------
    # 4) Remove files that should NOT be publicly accessible
    #    These exist in the repo but shouldn't be served.
    # ------------------------------------------------------------
    - /bin/rm -rf \
        "$DEPLOYPATH/.git" \
        "$DEPLOYPATH/.github" \
        "$DEPLOYPATH/.cpanel.yml" \
        "$DEPLOYPATH/.DS_Store" \
        "$DEPLOYPATH/.gitattributes" \
        "$DEPLOYPATH/README.md" \
        "$DEPLOYPATH/LICENSE"


    # ------------------------------------------------------------
    # 5) Fix permissions (critical on shared hosting)
    #
    #    Directories must be 755 (drwxr-xr-x)
    #    Files must be 644 (-rw-r--r--)
    #
    #    Prevents "mystery 404" issues caused by
    #    Apache not being allowed to read/execute files.
    # ------------------------------------------------------------
    - /usr/bin/find "$DEPLOYPATH" -type d -exec /bin/chmod 755 {} \;
    - /usr/bin/find "$DEPLOYPATH" -type f -exec /bin/chmod 644 {} \;
